version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo Installing dependencies...
      - pip install -r requirements.txt || echo "No requirements.txt found"

  build:
    commands:
      - echo Build started...
      - python app.py > output.txt

artifacts:
  files:
    - app.py
    - output.txt
